# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c96e1fbbb08ad832e8adfc0664b685a78042cfe95c9d5ec7a0bc13e687cb4e941da1afcb9888d3c1499994d6fd656aca1cd3fc11a7f2882e8a4e0dde779988fc
  s3_access_key_id:  AKIAIAZLPGSO7W63KDLQ
  s3_secret: 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
  s3_bucket: localpic
  s3_region: eu-west-1

test:
  secret_key_base: 2471ad402e16e1d07fe8a1c4ec9f98300c56e36092e493253233a611966d1023d11c4e001feb92407b5a9b17e6a275a2dba05d88d90385967fa7af492f58324e
  s3_access_key_id: aws-key-id
  s3_secret: aws-secret
  s3_bucket: localpic
  s3_region: eu-west-1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
